# paths
train_path: dataset/train
test_path: dataset/test
ckpt_path: toch_ckpt

# files
class_file: class.txt

# training paramters
learning_rate: 0.01
input_size: 224
train_batch_size: 32
test_batch_size: 8
epochs: 2
train_steps: 60
test_steps: 25
patience: 10
delta: 0.0001
